### ISSUE TITLE
关于自建仓库后更新代码问题

### ISSUE THREAD

**Issue by ttt789-ppo** [catlair/BiliTools#36]
大佬，我参考别的项目找到一个同步脚本，需要用到PAT，改了一下仓库地址，但是有个问题，因为这个脚本是同步repo和workflow的，同步后原仓库workflow只有一个yaml，我原来的scf.yaml和同步脚本.yaml都会被覆盖删除，所以想不同步workflow只同步库，想来请教一下脚本还需要怎么改？
同步脚本的yaml文件代码如下:
```yaml
name: Sync(同步/升级部署脚本) #一般无需手动执行,部署脚本每次执行就是部署最新代码,这个脚本只是用来升级部署脚本,部署脚本基本不更新
on:
  schedule:
    - cron: '3 20 * * *'
  workflow_dispatch:
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11,需要repo和workflow权限
    runs-on: ubuntu-latest
    timeout-minutes: 3
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: sync tongbu
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/catlair/BiliTools"
          source_branch: "main"
          destination_branch: "main"
          github_token: ${{ secrets.PAT }}
```

**Comment by ttt789-ppo** [comment]
这个脚本同步是能同步，就是原来配置的推送scf的yaml和同步.yaml本身也没了

**Comment by KudouRan** [comment]
为什么要同步这个仓库

```yaml
name: bilibili-deploy

on:
  workflow_dispatch: # 手动触发

jobs:
  deploy-bilibili-tool:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Run Deploy
        timeout-minutes: ${{secrets.TIMEOUT_MINUTES || 15}} # 超时时间(分钟)
        run: |
          sudo docker catlair/bilitools-deploy:latest
          sudo docker run \
           --env BILI_CONFIG="${{ secrets.BILI_CONFIG }}" \
           --env TENCENT_SECRET_ID="${{ secrets.TENCENT_SECRET_ID }}" \
           --env TENCENT_SECRET_KEY="${{ secrets.TENCENT_SECRET_KEY }}" \
           --env RUN_SCF_ALL=y \
           -i --rm  \
           catlair/bilitools-deploy:latest
```
