### ISSUE TITLE
GA运行时的问题

### ISSUE THREAD

**Issue by yehuzhucha** [catlair/BiliTools#53]
大佬好，在按照[GA运行](https://github.com/catlair/BiliTools/blob/main/docs/%E4%BD%BF%E7%94%A8Action%E8%BF%90%E8%A1%8C.md)操作后，手动执行一切正常，但似乎不会自动执行，不知该如何解决，由此想向大佬请教一下！

**Comment by catlair** [comment]
corn表达式是正确的吗，能发出来看看？

**Comment by yehuzhucha** [comment]
![image](https://user-images.githubusercontent.com/70362459/155878802-24d9658c-6e52-4e40-b4ce-b14f8a1b1a3c.png))
每晚18点26分执行

**Comment by KudouRan** [comment]
> ![image](https://user-images.githubusercontent.com/70362459/155878802-24d9658c-6e52-4e40-b4ce-b14f8a1b1a3c.png)) 每晚18点26分执行

这是一个很简单的错误，但是一直没被发现（没人用）

注意缩进，原文档中存在缩进错误

```yaml
name: gh-release

on:
  schedule: # 计划任务触发
    - cron: '55 11 * * *'

jobs:
  build-docker:
    runs-on: ubuntu-latest
    environment: Build
```
